name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  py-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14-dev"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: nox -s test

  # TODO: Could we switch over to gather coverage from the normal test runs and combining
  # the result once https://github.com/nedbat/coveragepy/issues/1002 is fixed?
  upload-coverage:
    # needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Record coverage
        run: nox -s test-coverage

      - name: Upload coverage
        uses: paambaati/codeclimate-action@f429536ee076d758a24705203199548125a28ca7
        env:
          CC_TEST_REPORTER_ID: 6afbda1b66ce6caab04965d92bee9ab4b02afef58568c6402455b25032b8b865
        with:
          coverageLocations: .coverage.xml:coverage.py

      - name: Archive coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: coverage
          path: ./coverage_html
          if-no-files-found: error
